### ISSUE TITLE
Figure 3 Script

### ISSUE THREAD

**Issue by RicardoRH96** [HKU-SPH-COVID-19-Genomics-Consortium/HK-SARS-CoV-2-genomic-epidemiology#1]
Hello, I have been following this paper since it was uploaded as a pre-print.
First of all, congratulations for this amazing research!
Could you please share the script for Figure 3? 
I am working with BDSKY data and would like to learn how to plot Re as you did, thanks in advance

**Comment by Koohoko** [comment]
Hi Ricardo,

Thanks for your email and interest in our paper!
Would you please check if these codes
<https://github.com/HKU-SPH-COVID-19-Genomics-Consortium/HK-SARS-CoV-2-genomic-epidemiology/tree/master/scripts/BDSS>
can
be helpful?

Best,
Haogao

**Comment by RicardoRH96** [comment]
Hi Haogao, indeed those codes work for me in order to visualize BDSKY results using skylinetools.
But my interest is in knowing how to turn these plots into the visualization done by you in figure 3 where you overlapped Re over sequence number through time and the subsequent "beautification".
I see you plot it as a ggplot object (ribbon+line) and transform the X axis into epiweeks.
Also the way you plotted the phylogenetic tree on top is really interesting.

**Comment by tommy-lam** [comment]
Hi Ricardo. Some were done manually.

**Comment by RicardoRH96** [comment]
Thanks
