### ISSUE TITLE
could you please tell me how to know the length.out?

### ISSUE THREAD

**Issue by liamxg** [HKU-SPH-COVID-19-Genomics-Consortium/HK-SARS-CoV-2-genomic-epidemiology#2]

**Comment by liamxg** [comment]
<img width="837" alt="image" src="https://user-images.githubusercontent.com/46078579/199418673-6a8d4feb-ba6c-49e3-b917-584d3918eee6.png">

**Comment by liamxg** [comment]
@Koohoko @dcadam

**Comment by Koohoko** [comment]
> <img alt="image" width="837" src="https://user-images.githubusercontent.com/46078579/199418673-6a8d4feb-ba6c-49e3-b917-584d3918eee6.png">

Hi Liamxg, I suggest maybe have to try the parameter manually.

**Comment by liamxg** [comment]
could you please tell me manually based on what?

**Comment by liamxg** [comment]
@Koohoko

**Comment by Koohoko** [comment]
@joetsui1994 Hi Joseph, would you have any thoughts on how to determine the `length.out` here?

https://github.com/HKU-SPH-COVID-19-Genomics-Consortium/HK-SARS-CoV-2-genomic-epidemiology/blob/8f3beee60c97e137c7d3c1ffe8bc14d1ee75104d/scripts/BDSS/Wave4_BDSS_Re_Plot.R#L20

**Comment by joetsui1994** [comment]
Hi Haogao, if I remember correctly this was determined somewhat arbitrarily by trying out different lengths. But in retrospect, since the change time points were fixed rather than estimated, it was perhaps unnecessary to use gridding and simply plot the estimates for the corresponding time intervals as specified in the model setup.

**Comment by Koohoko** [comment]
> Hi Haogao, if I remember correctly this was determined somewhat arbitrarily by trying out different lengths. But in retrospect, since the change time points were fixed rather than estimated, it was perhaps unnecessary to use gridding and simply plot the estimates for the corresponding time intervals as specified in the model setup.

Thank you very much!

**Comment by Koohoko** [comment]
> could you please tell me manually based on what?

Hi @liamxg, I hope the additional information from Joseph (above) can help.

**Comment by liamxg** [comment]
@Koohoko @joetsui1994 sorry, still confused about this.
